INSERT INTO travel ( 
flight_number,
departure_city,
departure_time,
arrival_city,
arrival_time,
duration,
aircraft_type,
return_flight_number,
return_departure_city,
return_departure_time,
return_arrival_city,
return_arrival_time,
return_duration,
return_aircraft_type,
total_cost,
cabin,
return_cabin,
card_type,
card_number,
expiration_month,
expiration_year,
cvv,
card_first_name,
card_last_name, 
confirmation,
member_id )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
RETURNING *;